import React, { useState } from "react";
import { PageHeader } from "@/components/common/PageHeader";
import { StatusBadge } from "@/components/common/StatusBadge";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Clock, DollarSign, Users, Briefcase, GraduationCap, CheckCircle, Download } from "lucide-react";
import { toast } from "sonner";

const TYPES = [
  { id: "time", label: "Time Summary", desc: "Total hours by staff/engagement", icon: Clock },
  { id: "billing", label: "Client Billing", desc: "Invoices and collections", icon: DollarSign },
  { id: "util", label: "Resource Utilisation", desc: "Capacity and workload", icon: Users },
  { id: "status", label: "Engagement Status", desc: "Progress and milestones", icon: Briefcase },
  { id: "training", label: "Training Progress", desc: "Learning completion", icon: GraduationCap },
  { id: "approval", label: "Approval Summary", desc: "Pending and approved hours", icon: CheckCircle },
];

const RECENT = [
  { name: "Time Summary - Feb 2026", type: "Time Summary", by: "John Carter", date: "2026-02-09", status: "Ready" },
  { name: "Client Billing - Q4 2025", type: "Client Billing", by: "Lisa Park", date: "2026-02-08", status: "Ready" },
  { name: "Resource Utilization - Jan 2026", type: "Resource Utilisation", by: "John Carter", date: "2026-02-05", status: "Processing" },
  { name: "Engagement Status - Q1 2026", type: "Engagement Status", by: "Lisa Park", date: "2026-01-31", status: "Ready" },
  { name: "Training Progress - 2025", type: "Training Progress", by: "John Carter", date: "2026-01-15", status: "Archived" },
];

const Reports = () => {
  const [genType, setGenType] = useState(null);

  return (
    <div data-testid="reports-page">
      <PageHeader title="Reports" description="Generate and schedule reports for partners and stakeholders" />

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-6">
        {TYPES.map((t) => (
          <Card key={t.id} className="p-5">
            <div className="flex items-start justify-between mb-3">
              <div className="h-10 w-10 rounded-md bg-primary/10 text-primary flex items-center justify-center"><t.icon className="h-5 w-5" /></div>
            </div>
            <h4 className="text-base font-semibold mb-1">{t.label}</h4>
            <p className="text-xs text-muted-foreground mb-4">{t.desc}</p>
            <Button data-testid={`generate-${t.id}`} size="sm" onClick={() => setGenType(t)}>Generate</Button>
          </Card>
        ))}
      </div>

      <Card className="overflow-hidden mb-6">
        <div className="p-4 border-b border-border"><h3 className="text-base font-semibold">Recent Reports</h3></div>
        <table className="w-full text-sm">
          <thead className="bg-muted/40 text-[11px] uppercase text-muted-foreground"><tr><th className="text-left py-2 px-4">Name</th><th className="text-left py-2 px-4">Type</th><th className="text-left py-2 px-4">Generated By</th><th className="text-left py-2 px-4">Date</th><th className="text-left py-2 px-4">Status</th><th className="text-right py-2 px-4">Action</th></tr></thead>
          <tbody>
            {RECENT.map((r, i) => (
              <tr key={i} className="border-t border-border">
                <td className="py-2.5 px-4 font-medium">{r.name}</td>
                <td className="py-2.5 px-4 text-muted-foreground">{r.type}</td>
                <td className="py-2.5 px-4">{r.by}</td>
                <td className="py-2.5 px-4 text-muted-foreground">{r.date}</td>
                <td className="py-2.5 px-4"><StatusBadge status={r.status === "Ready" ? "Approved" : r.status === "Processing" ? "Pending" : "Inactive"} /></td>
                <td className="py-2.5 px-4 text-right"><Button variant="ghost" size="icon" className="h-7 w-7"><Download className="h-3.5 w-3.5" /></Button></td>
              </tr>
            ))}
          </tbody>
        </table>
      </Card>

      <Card className="p-5">
        <div className="flex items-center justify-between mb-3"><h3 className="text-base font-semibold">Scheduled Reports</h3><Switch defaultChecked /></div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
          <div><Label>Frequency</Label>
            <Select defaultValue="Weekly"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>
              <SelectItem value="Daily">Daily</SelectItem><SelectItem value="Weekly">Weekly</SelectItem><SelectItem value="Monthly">Monthly</SelectItem>
            </SelectContent></Select></div>
          <div><Label>Recipients (comma-separated)</Label><Input placeholder="partners@firm.com, manager@firm.com" defaultValue="john@firm.com, lisa@firm.com" /></div>
          <div className="flex items-end"><Button className="w-full" onClick={() => toast.success("Schedule saved")}>Save Schedule</Button></div>
        </div>
      </Card>

      <Dialog open={!!genType} onOpenChange={(o) => !o && setGenType(null)}>
        <DialogContent>
          <DialogHeader><DialogTitle>Generate {genType?.label}</DialogTitle></DialogHeader>
          <div className="space-y-3">
            <div className="grid grid-cols-2 gap-3">
              <div><Label>From</Label><Input type="date" /></div>
              <div><Label>To</Label><Input type="date" /></div>
            </div>
            <div><Label>Format</Label>
              <Select defaultValue="pdf"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>
                <SelectItem value="pdf">PDF</SelectItem><SelectItem value="xlsx">Excel</SelectItem>
              </SelectContent></Select>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setGenType(null)}>Cancel</Button>
            <Button onClick={() => { setGenType(null); toast.success(`${genType?.label} queued`); }}>Generate</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default Reports;
